TGHM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='TGHM/index.html')),
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls')),
    path('customer/', include('customer.urls')),
    path('restaurant/', include('restaurant.urls')),
]

manager/urls.py
from django.urls import path, include
from . import views

app_name = 'manager'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('register_admin/', views.register_admin, name='register_admin'),
    path('login_admin/', views.login_admin, name='login_admin'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('add_station/', views.add_station, name='add_station'),
    path('add_train/', views.add_train, name='add_train'),
    path('change_station_status/', views.change_station_status, name='change_station_status'),
    path('edit_train/<int:train_id>', views.edit_train, name='edit_train'),
    path('statistics/', views.statistics, name='statistics'),
]

manager/models.py
from django.db import models

class Admin(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    def __str__(self):
        return self.username 

class Station(models.Model):
    name = models.CharField(max_length=50)
    lat = models.FloatField()
    lng = models.FloatField()
    visible = models.BooleanField(default=True)
    def __str__(self):
        return self.name

class Train(models.Model):
    name = models.CharField(max_length=50)
    stations = models.CharField(max_length=200, default='')
    def __str__(self):
        return self.name

manager/views.py
from telnetlib import STATUS
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from .models import Admin, Station, Train
from customer.models import Orders
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
# Create your views here.

# function to check if the input is a float
def isfloat(num):
    try:
        float(num)
        return True
    except ValueError:
        return False

# functions to login the manager 
def login(request):
    return render(request, 'manager/index.html')

def login_admin(request):
    obj = None
    for admin in Admin.objects.all():
        if admin.username == request.POST['username'] and admin.password == request.POST['password']:
            obj = admin
            break
    
    if obj is None:
        messages.error(request, 'Invalid username or password!')
        return HttpResponseRedirect('../login', status= 302)

    return HttpResponseRedirect('../dashboard')

# functions to register a management user
def register(request):
    return render(request, 'manager/register.html')

def register_admin(request):
    if request.POST['username'] != "" and request.POST['password'] == request.POST['re_password']:
        admin = Admin(username= request.POST['username'], password= request.POST['password'])
        admin.save()

        return HttpResponseRedirect('../dashboard')
    else :
        messages.error(request, 'Invalid username or passwords do not match!')
        return HttpResponseRedirect('../register')

# function to render dashboard page
def dashboard(request):
    context = {'station_list': Station.objects.all(), 'train_list': Train.objects.all()}
    return render(request, 'manager/dashboard.html',context)

# function to add a station to the system
def add_station(request):
    # return HttpResponse(request.POST['station'] + ' added successfully')
    if isfloat(request.POST['lat']) and isfloat(request.POST['lon']) and request.POST['station'] != "" and request.POST['lat']!= "" and request.POST['lon']!= "": 
        if -90 < float(request.POST['lat']) < 90 and -180 < float(request.POST['lon']) < 180:
            station = Station(name= request.POST['station'], lat= request.POST['lat'], lng= request.POST['lon'])
            station.save()
            return HttpResponseRedirect('../dashboard')
        else :
            messages.error(request, 'Latitude or Longitude out of range!')
            return HttpResponseRedirect('../dashboard', status= 302)
    else:
        messages.error(request, 'Invalid input!')
        return HttpResponseRedirect('../dashboard', status = 302)

# function to edit an existing train
def edit_train(request,train_id):

    if request.method == 'POST':
        train = get_object_or_404(Train, id=train_id)
        train.name = request.POST['train']
        train.stations = str(request.POST['start'])
        for i in range(0, len(request.POST)-4):
            train.stations += ' ' + str(request.POST[ 'r' + str(i+1)])
        train.stations += ' ' + str(request.POST['end'])
        train.save()

        return HttpResponseRedirect('../dashboard')

    train_name = Train.objects.get(id=train_id).name
    station_list = Train.objects.get(id=train_id).stations.split(" ")
    stations = []
    for station in station_list:
        stations.append(Station.objects.get(id=station))
    context = {'train_name': train_name, 'stations': stations,'station_list': Station.objects.all(), 'train_id': train_id}
    return HttpResponse(render(request, 'manager/edit_train.html', context))

# function to add a train to the system
def add_train(request):

    train = request.POST['train']
    start = request.POST['start']
    end = request.POST['end']
    station_list = str(request.POST['start'])
    for i in range(0, len(request.POST)-4):
        station_list += ' ' + str(request.POST[ 'r' + str(i+1)])
    station_list += ' ' + str(request.POST['end'])

    train = Train(name= train, stations= station_list)
    train.save()

    return HttpResponseRedirect('../dashboard')
    
# function to change the status of a station
def change_station_status(request):
    station = get_object_or_404(Station, id=request.GET['station_id'])
    station.visible = not station.visible
    station.save()

    return HttpResponseRedirect('../dashboard')

# function to plot the statistics for a route
def statistics(request):
    train = get_object_or_404(Train, id=request.GET['train_id'])
    station_list = train.stations.split(" ")
    stations = []

    for station in station_list:
        stations.append(Station.objects.get(id=station))

    deliv_cnt = 0
    undeliv_cnt = 0

    for order in Orders.objects.all():
        if order.status > 1:
            for station in stations:
                if station == order.restaurant.station:
                    deliv_cnt += 1
        else:
            for station in stations:
                if station == order.restaurant.station:
                    undeliv_cnt += 1

    context = {'delivered': deliv_cnt, 'undelivered': undeliv_cnt}
    
    return JsonResponse(context)

manager/templates/manager/edit_train.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Admin Dashboard</title>
    <style>
        .card {
            box-shadow: 5px 5px 20px rgb(63, 63, 63);
        }

        body {
            background: linear-gradient(to right, #003399, rgb(0, 255, 191));
        }
    </style>
</head>

<body>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">TGHM</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <br>
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Current Route</h4>
                <div class="card-text">
                    {% for station in stations %}
                    {{station.name}} ->
                    {% endfor %}

                    <form action="./{{train_id}}" method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1">Train Name</span>
                            <input type="text" class="form-control" value='{{train_name}}' id="train" name="train"
                                aria-label="Username" aria-describedby="basic-addon1">
                        </div>
                        <select class="form-select" name="start" id="start" aria-label="Default select example">
                            <option selected>Start Station</option>
                            {% for station in station_list %}
                            {% if station.visible == True %}
                            <option value="{{ station.id }}">{{ station.name }}</option>
                            {% endif %}
                            {% endfor %}
                        </select>
                        <div id="new_input"></div>
                        <a class="btn btn-outline-primary" onclick="add_station()">+ Add a station</a>
                        <select class="form-select" name="end" id="end" aria-label="Default select example">
                            <option selected>End Station</option>
                            {% for station in station_list %}
                            {% if station.visible == True %}
                            <option value="{{ station.id }}">{{ station.name }}</option>
                            {% endif %}
                            {% endfor %}
                        </select>
                        <br>
                        <button type="submit" class="btn btn-primary">Add</button>
                    </form>
                </div>
            </div>
        </div>

    </div>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>

    <script>

        var i = 1;

        function add_station() {
            const new_input = document.createElement('select');
            new_input.className = 'form-select';
            new_input.id = 'r' + i;
            new_input.name = 'r' + i;
            i++;
            new_input.innerHTML = '<option selected>Station</option>';
            {% for station in station_list %}
            {% if station.visible == True %}
            new_input.innerHTML += '<option value="{{ station.id }}">{{ station.name }}</option>';
            {% endif %}
            {% endfor %}
            document.getElementById('new_input').appendChild(new_input);
        }
    </script>
</body>

</html>

manager/templates/manager/index.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Admin Panel Log in</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Admin Panel Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css'>
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'><link rel="stylesheet" href="./style.css">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 login-box">
                <div class="col-lg-12 login-key">
                    <i class="fa fa-key" aria-hidden="true"></i>
                </div>
                <div class="col-lg-12 login-title">
                    ADMIN PANEL
                </div>

                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">
                        <form action = "{% url 'manager:login_admin' %}", method = "post">
                            {% csrf_token %}    
                            <div class="form-group">
                                <label class="form-control-label">USERNAME</label>
                                <input type="text" class="form-control" name="username" id="username">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">PASSWORD</label>
                                <input type="password" class="form-control" name="password" id="password">
                            </div>

                            <div class="col-lg-12 loginbttm">
                                <div class="col-lg-6 login-btm login-text">
                                    <!-- Error Message -->
                                    {% if messages %}
                                    <ul class="messages">
                                        {% for message in messages %}
                                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                        {% endfor %}
                                    </ul>
                                    {% endif %}
                                </div>
                                <div class="col-lg-6 login-btm login-button">
                                    <button type="submit" class="btn btn-outline-primary">LOGIN</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-3 col-md-2"></div>
            </div>
        </div>
<!-- partial -->
  

        <style>
                body {
                background: #222D32;
                font-family: 'Roboto', sans-serif;
            }

            .login-box {
                margin-top: 75px;
                height: auto;
                background: #1A2226;
                text-align: center;
                box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
            }

            .login-key {
                height: 100px;
                font-size: 80px;
                line-height: 100px;
                background: -webkit-linear-gradient(#27EF9F, #0DB8DE);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
            }

            .login-title {
                margin-top: 15px;
                text-align: center;
                font-size: 30px;
                letter-spacing: 2px;
                margin-top: 15px;
                font-weight: bold;
                color: #ECF0F5;
            }

            .login-form {
                margin-top: 25px;
                text-align: left;
            }

            input[type=text] {
                background-color: #1A2226;
                border: none;
                border-bottom: 2px solid #0DB8DE;
                border-top: 0px;
                border-radius: 0px;
                font-weight: bold;
                outline: 0;
                margin-bottom: 20px;
                padding-left: 0px;
                color: #ECF0F5;
            }

            input[type=password] {
                background-color: #1A2226;
                border: none;
                border-bottom: 2px solid #0DB8DE;
                border-top: 0px;
                border-radius: 0px;
                font-weight: bold;
                outline: 0;
                padding-left: 0px;
                margin-bottom: 20px;
                color: #ECF0F5;
            }

            .form-group {
                margin-bottom: 40px;
                outline: 0px;
            }

            .form-control:focus {
                border-color: inherit;
                -webkit-box-shadow: none;
                box-shadow: none;
                border-bottom: 2px solid #0DB8DE;
                outline: 0;
                background-color: #1A2226;
                color: #ECF0F5;
            }

            input:focus {
                outline: none;
                box-shadow: 0 0 0;
            }

            label {
                margin-bottom: 0px;
            }

            .form-control-label {
                font-size: 10px;
                color: #6C6C6C;
                font-weight: bold;
                letter-spacing: 1px;
            }

            .btn-outline-primary {
                border-color: #0DB8DE;
                color: #0DB8DE;
                border-radius: 0px;
                font-weight: bold;
                letter-spacing: 1px;
                box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
            }

            .btn-outline-primary:hover {
                background-color: #0DB8DE;
                right: 0px;
            }

            .login-btm {
                float: left;
            }

            .login-button {
                padding-right: 0px;
                text-align: right;
                margin-bottom: 25px;
            }

            .login-text {
                text-align: left;
                padding-left: 0px;
                color: #A2A4A4;
            }

            .loginbttm {
                padding: 0px;
            }
        </style>
</body>
</html>

manager/templates/manager/register.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Admin-Register</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Admin Panel Register</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css'>
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'><link rel="stylesheet" href="./style.css">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 login-box">
                <div class="col-lg-12 login-key">
                    <i class="fa fa-key" aria-hidden="true"></i>
                </div>
                <div class="col-lg-12 login-title">
                    Register
                </div>

                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">
                        <form action="{% url 'manager:register_admin' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="form-control-label">USERNAME</label>
                                <input type="text" class="form-control" name = "username" id = "username">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">PASSWORD</label>
                                <input type="password" class="form-control" name="password" id = "password">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">RE-TYPE PASSWORD</label>
                                <input type="password" class="form-control" name = "re_password" id = "re_password">
                            </div>

                            <div class="col-lg-12 loginbttm">
                                <div class="col-lg-6 login-btm login-text">
                                    <!-- Error Message -->
                                    {% if messages %}
                                    <ul class="messages">
                                        {% for message in messages %}
                                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                        {% endfor %}
                                    </ul>
                                    {% endif %}
                                </div>
                                <div class="col-lg-6 login-btm login-button">
                                    <button type="submit" class="btn btn-outline-primary">Register</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-3 col-md-2"></div>
            </div>
        </div>
<!-- partial -->
  

        <style>
            body {
                background: #222D32;
                font-family: 'Roboto', sans-serif;
            }

            .login-box {
                margin-top: 75px;
                height: auto;
                background: #1A2226;
                text-align: center;
                box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
            }

            .login-key {
                height: 100px;
                font-size: 80px;
                line-height: 100px;
                background: -webkit-linear-gradient(#27EF9F, #0DB8DE);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
            }

            .login-title {
                margin-top: 15px;
                text-align: center;
                font-size: 30px;
                letter-spacing: 2px;
                margin-top: 15px;
                font-weight: bold;
                color: #ECF0F5;
            }

            .login-form {
                margin-top: 25px;
                text-align: left;
            }

            input[type=text] {
                background-color: #1A2226;
                border: none;
                border-bottom: 2px solid #0DB8DE;
                border-top: 0px;
                border-radius: 0px;
                font-weight: bold;
                outline: 0;
                margin-bottom: 20px;
                padding-left: 0px;
                color: #ECF0F5;
            }

            input[type=password] {
                background-color: #1A2226;
                border: none;
                border-bottom: 2px solid #0DB8DE;
                border-top: 0px;
                border-radius: 0px;
                font-weight: bold;
                outline: 0;
                padding-left: 0px;
                margin-bottom: 20px;
                color: #ECF0F5;
            }

            .form-group {
                margin-bottom: 40px;
                outline: 0px;
            }

            .form-control:focus {
                border-color: inherit;
                -webkit-box-shadow: none;
                box-shadow: none;
                border-bottom: 2px solid #0DB8DE;
                outline: 0;
                background-color: #1A2226;
                color: #ECF0F5;
            }

            input:focus {
                outline: none;
                box-shadow: 0 0 0;
            }

            label {
                margin-bottom: 0px;
            }

            .form-control-label {
                font-size: 10px;
                color: #6C6C6C;
                font-weight: bold;
                letter-spacing: 1px;
            }

            .btn-outline-primary {
                border-color: #0DB8DE;
                color: #0DB8DE;
                border-radius: 0px;
                font-weight: bold;
                letter-spacing: 1px;
                box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
            }

            .btn-outline-primary:hover {
                background-color: #0DB8DE;
                right: 0px;
            }

            .login-btm {
                float: left;
            }

            .login-button {
                padding-right: 0px;
                text-align: right;
                margin-bottom: 25px;
            }

            .login-text {
                text-align: left;
                padding-left: 0px;
                color: #A2A4A4;
            }

            .loginbttm {
                padding: 0px;
            }
        </style>
</body>
</html>