TGHM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='TGHM/index.html')),
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls')),
    path('customer/', include('customer.urls')),
    path('restaurant/', include('restaurant.urls')),
]

customer/urls.py
from django.urls import path, include
from . import views

app_name = 'customer'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('register_customer/', views.register_customer, name='register_customer'),
    path('login_customer/', views.login_customer, name='login_customer'),
    path('dashboard/<int:customer_id>',views.dashboard,name='dashboard'),
    path('dashboard/fetch_station/',views.fetch_station,name='fetch_station'),
    path('dashboard/fetch_food/', views.fetch_food, name='fetch_food'),
    path('dashboard/get_time/', views.get_time, name='get_time'),
    path('place_order/<int:customer_id>', views.place_order, name='place_order'),
    path('change_status/<int:order_id>', views.change_status, name='change_status'),
]

customer/models.py
# from asyncio.windows_events import NULL
from datetime import datetime
from django.db import models
from manager.models import Station
from restaurant.models import Restaurant, FoodItem

class Customer(models.Model):
    username = models.CharField(max_length= 20)
    password = models.CharField(max_length= 20)
    phone_number = models.CharField(max_length= 10, default = 0)
    def __str__(self):
        return self.username

class Orders(models.Model):
    food_item = models.IntegerField()
    restaurant = models.ForeignKey(Restaurant, on_delete= models.CASCADE, default=None)
    customer = models.ForeignKey(Customer, on_delete= models.CASCADE, default=None)
    time = models.DateTimeField(default= datetime.now())
    status = models.IntegerField(default=0)
    
    def __str__(self):
        return FoodItem.objects.get(id = self.food_item).name + ", " + self.restaurant.name + ", " + str(self.time)

customer/views.py
import math
from wsgiref.util import request_uri
from django.shortcuts import render, get_object_or_404
import customer
from django.contrib import messages
from customer.models import Customer, Orders
from restaurant.models import FoodItem, Restaurant
from manager.models import Station, Train
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

import json
# Create your views here.

# login functions
def login(request):
    return render(request, 'customer/index.html')

def login_customer(request):
    obj = None
    for customer in Customer.objects.all():
        if customer.username == request.POST['username'] and customer.password == request.POST['password'] and customer.username!= "" and customer.password!= "":
            obj = customer
            break
    
    if obj is None:
        messages.error(request, 'Invalid Credentials!')
        return HttpResponseRedirect('../login/', status=302)

    return HttpResponseRedirect('../dashboard/' + str(obj.id))

# register functions
def register(request):
    return render(request, 'customer/register.html')

def register_customer(request):
    if request.POST['password'] == request.POST['re_password'] and request.POST['password']!= "" and request.POST['username']!= "" : 
        customer = Customer(username= request.POST['username'], password= request.POST['password'], phone_number = request.POST['phone_number'])

        if Customer.objects.filter(username=customer.username, password = customer.password, phone_number = customer.phone_number).exists():
            return HttpResponseRedirect('../dashboard/' + str(Customer.objects.filter(username=customer.username, password = customer.password)[0].id))
        
        customer.save()
        return HttpResponseRedirect('../dashboard/' + str(customer.id))
    else: 
        messages.error(request, 'Invalid username, mobile number or passwords do not match!')
        return HttpResponseRedirect('../register/', status = 302)

# function to display the dashboard
def dashboard(request, customer_id):
    customer = Customer.objects.get(id=customer_id)
    order_list  = Orders.objects.filter(customer=customer)
    context = {'order_list': order_list, 'customer': customer, 'train_list': Train.objects.all(), 'food_list': FoodItem.objects.all()}
    return render(request, 'customer/dashboard.html', context)

# function to fetch the station list and restaurant list corresponding to the train
def fetch_station(request):
    station = Train.objects.get(id=request.GET['train_id']).stations.split(' ')
    station_list, id_list = [],[]
    for i in station:
        id_list.append(i)
        station_list.append(Station.objects.get(id=i).name)

    restaurant_list = []
    

    for id in id_list:
        res_list = Restaurant.objects.filter(station=id)

        for res in  res_list:
            if res.id is not None:
                restaurant_list.append([res.id, res.name])
    

    return JsonResponse({'station_list': station_list, 'id_list': id_list, 'restaurant_list': restaurant_list})

# function to fetch the food item list corresponding to the selected restaurant
def fetch_food(request):
    restaurant = Restaurant.objects.get(id=request.GET['restaurant_id'])
    food_list = FoodItem.objects.filter(restaurant=restaurant)

    foods = []

    for food in food_list:
        foods.append([food.id, food.name, food.price])

    return JsonResponse({'food_list': foods})

# function to get the travel-time of delivery
def get_time(request):

    def haversine(lat1, lon1, lat2, lon2):
        # distance between latitudes
        # and longitudes
        dLat = (lat2 - lat1) * math.pi / 180.0
        dLon = (lon2 - lon1) * math.pi / 180.0
    
        # convert to radians
        lat1 = (lat1) * math.pi / 180.0
        lat2 = (lat2) * math.pi / 180.0
    
        # apply formulae
        a = (pow(math.sin(dLat / 2), 2) +
            pow(math.sin(dLon / 2), 2) *
                math.cos(lat1) * math.cos(lat2));
        rad = 6371
        c = 2 * math.asin(math.sqrt(a))
        return rad * c

    restaurant_station = Restaurant.objects.get(id=request.GET['restaurant_id']).station
    food = FoodItem.objects.get(id=request.GET['food_id'])
    train_station = []
    temp = Train.objects.get(id=request.GET['train_id']).stations.split(' ')
    for i in temp:
        train_station.append(Station.objects.get(id=i))
    current_station = Station.objects.get(id=request.GET['current_station_id'])

    speed = 100

    current_station_index = train_station.index(current_station)
    restaurant_station_index = train_station.index(restaurant_station)
    if current_station_index > restaurant_station_index:
        return JsonResponse({'time': 'Delivery Not Possible'})
    elif current_station_index == restaurant_station_index:
        return JsonResponse({'time': '00 hr : 15 min : 00 sec' })
    else:
        distance = 0
        while current_station_index != restaurant_station_index:
            distance += haversine(current_station.lat, current_station.lng, train_station[current_station_index + 1].lat, train_station[current_station_index + 1].lng)
            current_station_index += 1
        time = distance / speed
        hr = int(time)
        min = int((time - hr) * 60)
        sec = int(((time - hr) * 60 - min) * 60)

        return JsonResponse({'time': str(hr) + " hr : " + str(min) + " min : " + str(sec) + " sec"})

# function to place an order
def place_order(request,customer_id):
    order = Orders(customer = Customer.objects.get(id=customer_id), restaurant = Restaurant.objects.get(id=request.POST['restaurant']), food_item = request.POST['food'])
    order.save()

    return HttpResponseRedirect('../dashboard/' + str(customer_id))

def change_status(request,order_id):
    order = Orders.objects.get(id=order_id)
    order.status += 1
    order.save()
    return HttpResponseRedirect('../dashboard/' + str(order.customer.id))

customer/templates/customer/index.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Admin Panel Log in</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Admin Panel Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css'>
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'><link rel="stylesheet" href="./style.css">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 login-box">
                <div class="col-lg-12 login-key">
                    <i class="fa fa-key" aria-hidden="true"></i>
                </div>
                <div class="col-lg-12 login-title">
                    Customer Login
                </div>

                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">
                        <form action = "{% url 'customer:login_customer' %}", method = "post">
                            {% csrf_token %}    
                            <div class="form-group">
                                <label class="form-control-label">USERNAME</label>
                                <input type="text" class="form-control" name="username" id="username">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">PASSWORD</label>
                                <input type="password" class="form-control" name="password" id="password">
                            </div>

                            <div class="col-lg-12 loginbttm">
                                <div class="col-lg-6 login-btm login-text">
                                    <a href="{% url 'customer:register' %}">Not Registered ?</a>
                                </div>
                                <div class="col-lg-6 login-btm login-text">
                                    <!-- Error Message -->
                                    {% if messages %}
                                    <ul class="messages">
                                        {% for message in messages %}
                                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                        {% endfor %}
                                    </ul>
                                    {% endif %}
                                </div>
                                <div class="col-lg-6 login-btm login-button">
                                    <button type="submit" class="btn btn-outline-primary">LOGIN</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-3 col-md-2"></div>
            </div>
        </div>
<!-- partial -->
  

        <style>
                body {
                background: #222D32;
                font-family: 'Roboto', sans-serif;
            }

            .login-box {
                margin-top: 75px;
                height: auto;
                background: #1A2226;
                text-align: center;
                box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
            }

            .login-key {
                height: 100px;
                font-size: 80px;
                line-height: 100px;
                background: -webkit-linear-gradient(#27EF9F, #0DB8DE);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
            }

            .login-title {
                margin-top: 15px;
                text-align: center;
                font-size: 30px;
                letter-spacing: 2px;
                margin-top: 15px;
                font-weight: bold;
                color: #ECF0F5;
            }

            .login-form {
                margin-top: 25px;
                text-align: left;
            }

            input[type=text] {
                background-color: #1A2226;
                border: none;
                border-bottom: 2px solid #0DB8DE;
                border-top: 0px;
                border-radius: 0px;
                font-weight: bold;
                outline: 0;
                margin-bottom: 20px;
                padding-left: 0px;
                color: #ECF0F5;
            }

            input[type=password] {
                background-color: #1A2226;
                border: none;
                border-bottom: 2px solid #0DB8DE;
                border-top: 0px;
                border-radius: 0px;
                font-weight: bold;
                outline: 0;
                padding-left: 0px;
                margin-bottom: 20px;
                color: #ECF0F5;
            }

            .form-group {
                margin-bottom: 40px;
                outline: 0px;
            }

            .form-control:focus {
                border-color: inherit;
                -webkit-box-shadow: none;
                box-shadow: none;
                border-bottom: 2px solid #0DB8DE;
                outline: 0;
                background-color: #1A2226;
                color: #ECF0F5;
            }

            input:focus {
                outline: none;
                box-shadow: 0 0 0;
            }

            label {
                margin-bottom: 0px;
            }

            .form-control-label {
                font-size: 10px;
                color: #6C6C6C;
                font-weight: bold;
                letter-spacing: 1px;
            }

            .btn-outline-primary {
                border-color: #0DB8DE;
                color: #0DB8DE;
                border-radius: 0px;
                font-weight: bold;
                letter-spacing: 1px;
                box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
            }

            .btn-outline-primary:hover {
                background-color: #0DB8DE;
                right: 0px;
            }

            .login-btm {
                float: left;
            }

            .login-button {
                padding-right: 0px;
                text-align: right;
                margin-bottom: 25px;
            }

            .login-text {
                text-align: left;
                padding-left: 0px;
                color: #A2A4A4;
            }

            .loginbttm {
                padding: 0px;
            }
        </style>
</body>
</html>

customer/templates/customer/register.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Admin-Register</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Admin Panel Register</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css'>
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'><link rel="stylesheet" href="./style.css">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 login-box">
                <div class="col-lg-12 login-key">
                    <i class="fa fa-key" aria-hidden="true"></i>
                </div>
                <div class="col-lg-12 login-title">
                    Register Customer
                </div>

                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">
                        <form action="{% url 'customer:register_customer' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="form-control-label">USERNAME</label>
                                <input type="text" class="form-control" name = "username" id = "username">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">PASSWORD</label>
                                <input type="password" class="form-control" name="password" id = "password">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">RE-TYPE PASSWORD</label>
                                <input type="password" class="form-control" name = "re_password" id = "re_password">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">PHONE NUMBER</label>
                                <input type="text" class="form-control" name = "phone_number" id = "phone_number">
                            </div>
                            <div class="col-lg-12 loginbttm">
                                <div class="col-lg-6 login-btm login-text">
                                    <!-- Error Message -->
                                    {% if messages %}
                                    <ul class="messages">
                                        {% for message in messages %}
                                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                        {% endfor %}
                                    </ul>
                                    {% endif %}
                                </div>
                                <div class="col-lg-6 login-btm login-button">
                                    <button type="submit" class="btn btn-outline-primary">Register</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-3 col-md-2"></div>
            </div>
        </div>
<!-- partial -->
  

        <style>
            body {
                background: #222D32;
                font-family: 'Roboto', sans-serif;
            }

            .login-box {
                margin-top: 75px;
                height: auto;
                background: #1A2226;
                text-align: center;
                box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
            }

            .login-key {
                height: 100px;
                font-size: 80px;
                line-height: 100px;
                background: -webkit-linear-gradient(#27EF9F, #0DB8DE);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
            }

            .login-title {
                margin-top: 15px;
                text-align: center;
                font-size: 30px;
                letter-spacing: 2px;
                margin-top: 15px;
                font-weight: bold;
                color: #ECF0F5;
            }

            .login-form {
                margin-top: 25px;
                text-align: left;
            }

            input[type=text] {
                background-color: #1A2226;
                border: none;
                border-bottom: 2px solid #0DB8DE;
                border-top: 0px;
                border-radius: 0px;
                font-weight: bold;
                outline: 0;
                margin-bottom: 20px;
                padding-left: 0px;
                color: #ECF0F5;
            }

            input[type=password] {
                background-color: #1A2226;
                border: none;
                border-bottom: 2px solid #0DB8DE;
                border-top: 0px;
                border-radius: 0px;
                font-weight: bold;
                outline: 0;
                padding-left: 0px;
                margin-bottom: 20px;
                color: #ECF0F5;
            }

            .form-group {
                margin-bottom: 40px;
                outline: 0px;
            }

            .form-control:focus {
                border-color: inherit;
                -webkit-box-shadow: none;
                box-shadow: none;
                border-bottom: 2px solid #0DB8DE;
                outline: 0;
                background-color: #1A2226;
                color: #ECF0F5;
            }

            input:focus {
                outline: none;
                box-shadow: 0 0 0;
            }

            label {
                margin-bottom: 0px;
            }

            .form-control-label {
                font-size: 10px;
                color: #6C6C6C;
                font-weight: bold;
                letter-spacing: 1px;
            }

            .btn-outline-primary {
                border-color: #0DB8DE;
                color: #0DB8DE;
                border-radius: 0px;
                font-weight: bold;
                letter-spacing: 1px;
                box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
            }

            .btn-outline-primary:hover {
                background-color: #0DB8DE;
                right: 0px;
            }

            .login-btm {
                float: left;
            }

            .login-button {
                padding-right: 0px;
                text-align: right;
                margin-bottom: 25px;
            }

            .login-text {
                text-align: left;
                padding-left: 0px;
                color: #A2A4A4;
            }

            .loginbttm {
                padding: 0px;
            }
        </style>
</body>
</html>