TGHM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='TGHM/index.html')),
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls')),
    path('customer/', include('customer.urls')),
    path('restaurant/', include('restaurant.urls')),
]

restaurant/urls.py
from django.urls import path, include
from . import views

app_name = 'restaurant'

urlpatterns = [
    # path('', views.login, name='login')
    path('login/', views.login, name='login'),
    path('dashboard/<int:restaurant_id>', views.dashboard, name='dashboard'),
    path('login_restaurant/', views.login_restaurant, name='login_restaurant'),
    path('register/', views.register, name='register'),
    path('register_restaurant/', views.register_restaurant, name='register_restaurant'),
    path('add_food/<int:restaurant_id>', views.add_food, name='add_food'),
    path('change_status/<int:order_id>', views.change_status, name='change_status'),
]

restaurant/models.py
from django.db import models
from manager.models import Station

# Create your models here.
class Restaurant(models.Model):
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=30)
    mobile = models.CharField(max_length=10)
    name = models.CharField(max_length=40)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name + ' , ' + self.station.name

class FoodItem(models.Model):
    name = models.CharField(max_length=40)
    price = models.IntegerField()
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    def __str__(self):
        return self.name + ' , ' + self.restaurant.name

restaurant/views.py
from unicodedata import name
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from matplotlib.style import context
from manager.models import Station
import restaurant
from .models import FoodItem, Restaurant
from customer.models import Orders

# Create your views here. 

# function to display the dashboard of the restaurant
def dashboard(request,restaurant_id):
    restaurant = Restaurant.objects.get(id=restaurant_id)
    food_list = FoodItem.objects.filter(restaurant_id=restaurant_id)
    order_list = Orders.objects.filter(restaurant_id=restaurant_id)
    context = {'restaurant': restaurant,'food_list': food_list, 'order_list': order_list}
    return render(request, 'restaurant/dashboard.html',context)

# functions to login
def login(request):
    return render(request, 'restaurant/index.html')

def login_restaurant(request):
    obj = None
    for restaurant in Restaurant.objects.all():
        if restaurant.username == request.POST['username'] and restaurant.password == request.POST['password'] and request.POST['username']!= "" and request.POST['password'] != "":
            obj = restaurant
            break
    if obj is None:
        messages.error(request, 'Invalid username or password!')
        return HttpResponseRedirect('../login/')
    
    return HttpResponseRedirect('../dashboard/' + str(obj.id))

# functions to register
def register(request):
    context = {'station_list': Station.objects.all()}
    return render(request, 'restaurant/register.html',context)

def register_restaurant(request):
    if request.POST['username']!= "" and request.POST['password'] == request.POST['re_password'] and request.POST['password']!= "" and request.POST['mobile']!= "": 
        obj = Restaurant(username=request.POST['username'], password=request.POST['password'], name=request.POST['name'], station= Station.objects.get(id=request.POST['station']))

        if Restaurant.objects.filter(username = obj.username, password = obj.password, mobile = obj.mobile).exists():
            return HttpResponseRedirect('../dashboard/' + str(Restaurant.objects.get(username = obj.username, password = obj.password, mobile = obj.mobile).id))
        obj.save()
            
        return HttpResponseRedirect('../dashboard/' + str(obj.id))
    else :
        messages.error(request, 'Error! Please fill all the fields correctly!')
        return HttpResponseRedirect('../register', status = 302)

# function to add a food item to the restaurant
def add_food(request, restaurant_id):
    restaurant = Restaurant.objects.get(id=restaurant_id)
    if request.POST['food_name']!= "" and request.POST['food_price'].isnumeric() and  float(request.POST['food_price'])>= 0:
        food = FoodItem(name=request.POST['food_name'], price=request.POST['food_price'], restaurant=restaurant)
        food.save()
        return HttpResponseRedirect('../dashboard/' + str(restaurant.id))
    
    else :
        messages.error(request, 'Error! Please fill all the fields correctly!')
        return HttpResponseRedirect('../dashboard/' + str(restaurant.id), status = 302)

def change_status(request,order_id):
    order = Orders.objects.get(id=order_id)
    order.status += 1
    order.save()
    return HttpResponseRedirect('../dashboard/' + str(order.restaurant.id))

restaurant/templates/restaurant/dashboard.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Restaurant-Dashboard</title>
    <style>
        .card{
            height: 300px;
            box-shadow: 5px 5px 20px rgb(63, 63, 63);
        }
        body{
            background: linear-gradient(to right, #003399, rgb(0, 255, 191) );
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">TGHM</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="./{{restaurant.id}}">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav><br>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Information</h5>
                        <div class="card-text">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col"></th>
                                        <th scope="col"></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Name:</td>
                                        <td>{{restaurant.name}}</td>
                                    </tr>
                                    <tr>
                                        <td>Username:</td>
                                        <td>{{restaurant.username}}</td>
                                    </tr>
                                    <tr>
                                        <td>Station:</td>
                                        <td>{{restaurant.station.name}}</td>
                                    </tr>
                                    <tr>
                                        <td>Phone Number:</td>
                                        <td>{{restaurant.mobile}}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Order Status</h5>
                        <div class="card-text">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">Order ID</th>
                                        <th scope="col">Food Item</th>
                                        <th scope="col"></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in order_list %}
                                    <tr>
                                        <td>{{order.id}}</td>
                                        {% for food in food_list %}
                                        {% if food.id == order.food_item %}
                                            <td>{{food.name}}</td>
                                        {% endif %}
                                        {% endfor %}
                                        {% if order.status == 0 %}
                                        <td><a class="btn btn-primary" href="/restaurant/change_status/{{order.id}}">Accept Order</a></td>
                                        {% elif order.status == 1 %}
                                        <td>Accepted</td>
                                        {% elif order.status == 2 %}
                                        <td>Delivered</td>
                                        {% endif %}
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Add Food Item</h5>
                        <div class="card-text">
                            <form action="/restaurant/add_food/{{restaurant.id}}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="food_name">Food Name</label>
                                    <input type="text" class="form-control" id="food_name" name="food_name"
                                        placeholder="Enter Food Name">
                                </div>
                                <div class="form-group">
                                    <label for="food_price">Food Price</label>
                                    <input type="text" class="form-control" id="food_price" name="food_price"
                                        placeholder="Enter Food Price">
                                </div>
                                <br><button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Menu</h5>
                        <div class="card-text">
                            {% if food_list %}
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">Food Item</th>
                                        <th scope="col">Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in food_list %}
                                    <tr>
                                        <td>{{item.name}}</td>
                                        <td>{{item.price}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            {% else %}
                            <p>No Food Items</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

</body>

</html>

restaurant/templates/restaurant/index.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Restaurant Panel Log in</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Restaurant Panel Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css'>
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'><link rel="stylesheet" href="./style.css">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 login-box">
                <div class="col-lg-12 login-key">
                    <i class="fa fa-key" aria-hidden="true"></i>
                </div>
                <div class="col-lg-12 login-title">
                    RESTAURANT PANEL
                </div>

                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">
                        <form action = "{% url 'restaurant:login_restaurant' %}", method = "post">
                            {% csrf_token %}    
                            <div class="form-group">
                                <label class="form-control-label">USERNAME</label>
                                <input type="text" class="form-control" name="username" id="username">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">PASSWORD</label>
                                <input type="password" class="form-control" name="password" id="password">
                            </div>

                            <div class="col-lg-12 loginbttm">
                                <div class="col-lg-6 login-btm login-text">
                                    <a href="{% url 'restaurant:register' %}">Not Registered ?</a>
                                </div>
                                <div class="col-lg-6 login-btm login-button">
                                    <button type="submit" class="btn btn-outline-primary">LOGIN</button>
                                </div>
                            </div>

                            <div class="col-lg-6 login-btm login-text">
                                <!-- Error Message -->
                                {% if messages %}
                                <ul class="messages">
                                    {% for message in messages %}
                                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>

                        </form>
                    </div>
                </div>
                <div class="col-lg-3 col-md-2"></div>
            </div>
        </div>
<!-- partial -->
  

        <style>
                body {
                background: #222D32;
                font-family: 'Roboto', sans-serif;
            }

            .login-box {
                margin-top: 75px;
                height: auto;
                background: #1A2226;
                text-align: center;
                box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
            }

            .login-key {
                height: 100px;
                font-size: 80px;
                line-height: 100px;
                background: -webkit-linear-gradient(#27EF9F, #0DB8DE);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
            }

            .login-title {
                margin-top: 15px;
                text-align: center;
                font-size: 30px;
                letter-spacing: 2px;
                margin-top: 15px;
                font-weight: bold;
                color: #ECF0F5;
            }

            .login-form {
                margin-top: 25px;
                text-align: left;
            }

            input[type=text] {
                background-color: #1A2226;
                border: none;
                border-bottom: 2px solid #0DB8DE;
                border-top: 0px;
                border-radius: 0px;
                font-weight: bold;
                outline: 0;
                margin-bottom: 20px;
                padding-left: 0px;
                color: #ECF0F5;
            }

            input[type=password] {
                background-color: #1A2226;
                border: none;
                border-bottom: 2px solid #0DB8DE;
                border-top: 0px;
                border-radius: 0px;
                font-weight: bold;
                outline: 0;
                padding-left: 0px;
                margin-bottom: 20px;
                color: #ECF0F5;
            }

            .form-group {
                margin-bottom: 40px;
                outline: 0px;
            }

            .form-control:focus {
                border-color: inherit;
                -webkit-box-shadow: none;
                box-shadow: none;
                border-bottom: 2px solid #0DB8DE;
                outline: 0;
                background-color: #1A2226;
                color: #ECF0F5;
            }

            input:focus {
                outline: none;
                box-shadow: 0 0 0;
            }

            label {
                margin-bottom: 0px;
            }

            .form-control-label {
                font-size: 10px;
                color: #6C6C6C;
                font-weight: bold;
                letter-spacing: 1px;
            }

            .btn-outline-primary {
                border-color: #0DB8DE;
                color: #0DB8DE;
                border-radius: 0px;
                font-weight: bold;
                letter-spacing: 1px;
                box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
            }

            .btn-outline-primary:hover {
                background-color: #0DB8DE;
                right: 0px;
            }

            .login-btm {
                float: left;
            }

            .login-button {
                padding-right: 0px;
                text-align: right;
                margin-bottom: 25px;
            }

            .login-text {
                text-align: left;
                padding-left: 0px;
                color: #A2A4A4;
            }

            .loginbttm {
                padding: 0px;
            }
        </style>
</body>
</html>

restaurant/templates/restaurant/register.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Restaurant-Register</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Restaurant Panel Register</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css'>
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'><link rel="stylesheet" href="./style.css">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 login-box">
                <div class="col-lg-12 login-key">
                    <i class="fa fa-key" aria-hidden="true"></i>
                </div>
                <div class="col-lg-12 login-title">
                    Register Restaurant
                </div>

                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">
                        <form action="{% url 'restaurant:register_restaurant' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="form-control-label">NAME</label>
                                <input type="text" class="form-control" name = "name" id = "name">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">USERNAME</label>
                                <input type="text" class="form-control" name = "username" id = "username">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">PASSWORD</label>
                                <input type="password" class="form-control" name="password" id = "password">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">RE-TYPE PASSWORD</label>
                                <input type="password" class="form-control" name = "re_password" id = "re_password">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">PHONE NUMBER</label>
                                <input type="text" class="form-control" name = "mobile" id = "mobile">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">Station</label>
                                <select class="form-select" id="station" name="station">
                                    <option>Select Station</option>
                                    {% for station in station_list %}
                                        {% if station.visible == True %}
                                        <option value="{{ station.id }}">{{ station.name }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-lg-12 loginbttm">
                                <div class="col-lg-6 login-btm login-text">
                                    <!-- Error Message -->
                                    {% if messages %}
                                    <ul class="messages">
                                        {% for message in messages %}
                                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                        {% endfor %}
                                    </ul>
                                    {% endif %}
                                </div>
                                <div class="col-lg-6 login-btm login-button">
                                    <button type="submit" class="btn btn-outline-primary">Register</button>
                                </div>

                                
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-3 col-md-2"></div>
            </div>
        </div>
<!-- partial -->
  

        <style>
            body {
                background: #222D32;
                font-family: 'Roboto', sans-serif;
            }

            .login-box {
                margin-top: 75px;
                height: auto;
                background: #1A2226;
                text-align: center;
                box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
            }

            .login-key {
                height: 100px;
                font-size: 80px;
                line-height: 100px;
                background: -webkit-linear-gradient(#27EF9F, #0DB8DE);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
            }

            .login-title {
                margin-top: 15px;
                text-align: center;
                font-size: 30px;
                letter-spacing: 2px;
                margin-top: 15px;
                font-weight: bold;
                color: #ECF0F5;
            }

            .login-form {
                margin-top: 25px;
                text-align: left;
            }

            input[type=text] {
                background-color: #1A2226;
                border: none;
                border-bottom: 2px solid #0DB8DE;
                border-top: 0px;
                border-radius: 0px;
                font-weight: bold;
                outline: 0;
                margin-bottom: 20px;
                padding-left: 0px;
                color: #ECF0F5;
            }

            input[type=password] {
                background-color: #1A2226;
                border: none;
                border-bottom: 2px solid #0DB8DE;
                border-top: 0px;
                border-radius: 0px;
                font-weight: bold;
                outline: 0;
                padding-left: 0px;
                margin-bottom: 20px;
                color: #ECF0F5;
            }

            .form-group {
                margin-bottom: 40px;
                outline: 0px;
            }

            .form-control:focus {
                border-color: inherit;
                -webkit-box-shadow: none;
                box-shadow: none;
                border-bottom: 2px solid #0DB8DE;
                outline: 0;
                background-color: #1A2226;
                color: #ECF0F5;
            }

            input:focus {
                outline: none;
                box-shadow: 0 0 0;
            }

            label {
                margin-bottom: 0px;
            }

            .form-control-label {
                font-size: 10px;
                color: #6C6C6C;
                font-weight: bold;
                letter-spacing: 1px;
            }

            .btn-outline-primary {
                border-color: #0DB8DE;
                color: #0DB8DE;
                border-radius: 0px;
                font-weight: bold;
                letter-spacing: 1px;
                box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
            }

            .btn-outline-primary:hover {
                background-color: #0DB8DE;
                right: 0px;
            }

            .login-btm {
                float: left;
            }

            .login-button {
                padding-right: 0px;
                text-align: right;
                margin-bottom: 25px;
            }

            .login-text {
                text-align: left;
                padding-left: 0px;
                color: #A2A4A4;
            }

            .loginbttm {
                padding: 0px;
            }
        </style>
</body>
</html>